version: '2'
config:
  slack_notify: true
  slack_channel: astra-ci
environment:
  BUILD_IMAGE: 'maven:3.6-jdk-11'
jobs:
  build_docker:
    steps:
      - build_image:
          buildkit: true
          dockerfile: docker/Dockerfile
  publish_docker:
    steps:
      - push_image
  deploy_dev:
    steps:
      - deploy_dev:
          cluster: dev
          namespace: astra
          workload: blockscout
          argocd_pipeline: generic-v2
          deployment_config: dev
  deploy_dev_v1:
    steps:
      - deploy_dev:
          cluster: dev
          namespace: astra
          workload: blockscout_v1
          argocd_pipeline: generic-v2
          deployment_config: dev_v1
  deploy_prod:
    steps:
      - deploy_production:
          workload: blockscout
          argocd_pipeline: generic-v2
          deployment_config: prod
workflows:
  jenkins_pipeline:
    jobs:
      - build_docker:
          filters:
            branches:
              only:
                - astra
                - dev
      - publish_docker:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - astra
                - dev
      - deploy_dev:
          requires:
            - publish_docker
          filters:
            branches:
              only:
                - dev
      - deploy_dev_v1:
          requires:
            - publish_docker
          filters:
            branches:
              only:
                - dev
      - deploy_prod:
          requires:
            - publish_docker
          filters:
            branches:
              only:
                - astra
deployment_config:
  dev:
    ingress:
      hosts:
        - host: blockscout.dev.tiki.services
          paths:
            - path: /
              port: '4000'
    replicaCount: 1
  dev_v1:
    ingress:
      hosts:
        - host: blockscout-v1.dev.tiki.services
          paths:
            - path: /
              port: '4000'
    replicaCount: 1
  prod:
    ingress:
      hosts:
        - host: blockscout.tiki.services
          paths:
            - path: /
              port: '4000'
    replicaCount: 1
